// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts,import_extension=none"
// @generated from file atlas.proto (package dm.atlas, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty } from "./shared_pb";
import { SignatureReturns } from "./atlas_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service dm.atlas.SignatureAtlasService
 */
export const SignatureAtlasService = {
  typeName: "dm.atlas.SignatureAtlasService",
  methods: {
    /**
     * @generated from rpc dm.atlas.SignatureAtlasService.List
     */
    list: {
      name: "List",
      I: Empty,
      O: SignatureReturns,
      kind: MethodKind.Unary,
    },
  }
} as const;

