// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/helloworld.proto (package helloworld, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloReply, HelloRequest } from "./helloworld_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helloworld.Greeter
 */
export const Greeter = {
  typeName: "helloworld.Greeter",
  methods: {
    /**
     * Our SayHello rpc accepts HelloRequests and returns HelloReplies
     *
     * @generated from rpc helloworld.Greeter.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: HelloRequest,
      O: HelloReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

